import { DefaultTheme } from 'vitepress';
export const apiSidebar: DefaultTheme.SidebarItem[] = [{
  "text": "Classes",
  "items": [{
    "text": "Animate",
    "link": "/api/classes/Animate.md"
  }, {
    "text": "AnimateEvent",
    "link": "/api/classes/AnimateEvent.md"
  }, {
    "text": "AnimateList",
    "link": "/api/classes/AnimateList.md"
  }, {
    "text": "Arrow",
    "link": "/api/classes/Arrow.md"
  }, {
    "text": "ArrowData",
    "link": "/api/classes/ArrowData.md"
  }, {
    "text": "EllipseBox",
    "link": "/api/classes/EllipseBox.md"
  }, {
    "text": "ImageBox",
    "link": "/api/classes/ImageBox.md"
  }, {
    "text": "PathBox",
    "link": "/api/classes/PathBox.md"
  }, {
    "text": "PolygonBox",
    "link": "/api/classes/PolygonBox.md"
  }, {
    "text": "StarBox",
    "link": "/api/classes/StarBox.md"
  }, {
    "text": "EllipseBoxData",
    "link": "/api/classes/EllipseBoxData.md"
  }, {
    "text": "ImageBoxData",
    "link": "/api/classes/ImageBoxData.md"
  }, {
    "text": "PathBoxData",
    "link": "/api/classes/PathBoxData.md"
  }, {
    "text": "PolygonBoxData",
    "link": "/api/classes/PolygonBoxData.md"
  }, {
    "text": "StarBoxData",
    "link": "/api/classes/StarBoxData.md"
  }, {
    "text": "Editor",
    "link": "/api/classes/Editor.md"
  }, {
    "text": "EditBox",
    "link": "/api/classes/EditBox.md"
  }, {
    "text": "EditPoint",
    "link": "/api/classes/EditPoint.md"
  }, {
    "text": "EditSelect",
    "link": "/api/classes/EditSelect.md"
  }, {
    "text": "SelectArea",
    "link": "/api/classes/SelectArea.md"
  }, {
    "text": "Stroker",
    "link": "/api/classes/Stroker.md"
  }, {
    "text": "EditorEvent",
    "link": "/api/classes/EditorEvent.md"
  }, {
    "text": "EditorGroupEvent",
    "link": "/api/classes/EditorGroupEvent.md"
  }, {
    "text": "EditorMoveEvent",
    "link": "/api/classes/EditorMoveEvent.md"
  }, {
    "text": "EditorRotateEvent",
    "link": "/api/classes/EditorRotateEvent.md"
  }, {
    "text": "EditorScaleEvent",
    "link": "/api/classes/EditorScaleEvent.md"
  }, {
    "text": "EditorSkewEvent",
    "link": "/api/classes/EditorSkewEvent.md"
  }, {
    "text": "InnerEditorEvent",
    "link": "/api/classes/InnerEditorEvent.md"
  }, {
    "text": "EditTool",
    "link": "/api/classes/EditTool.md"
  }, {
    "text": "InnerEditor",
    "link": "/api/classes/InnerEditor.md"
  }, {
    "text": "LineEditTool",
    "link": "/api/classes/LineEditTool.md"
  }, {
    "text": "TransformTool",
    "link": "/api/classes/TransformTool.md"
  }, {
    "text": "Finder",
    "link": "/api/classes/Finder.md"
  }, {
    "text": "Flow",
    "link": "/api/classes/Flow.md"
  }, {
    "text": "HTMLText",
    "link": "/api/classes/HTMLText.md"
  }, {
    "text": "HTMLTextData",
    "link": "/api/classes/HTMLTextData.md"
  }, {
    "text": "Robot",
    "link": "/api/classes/Robot.md"
  }, {
    "text": "RobotData",
    "link": "/api/classes/RobotData.md"
  }, {
    "text": "ScrollBar",
    "link": "/api/classes/ScrollBar.md"
  }, {
    "text": "Scroller",
    "link": "/api/classes/Scroller.md"
  }, {
    "text": "TextEditor",
    "link": "/api/classes/TextEditor.md"
  }, {
    "text": "Transformer",
    "link": "/api/classes/Transformer.md"
  }, {
    "text": "LeaferCanvas",
    "link": "/api/classes/LeaferCanvas.md"
  }, {
    "text": "CanvasManager",
    "link": "/api/classes/CanvasManager.md"
  }, {
    "text": "LeaferCanvasBase",
    "link": "/api/classes/LeaferCanvasBase.md"
  }, {
    "text": "Debug",
    "link": "/api/classes/Debug.md"
  }, {
    "text": "LeafData",
    "link": "/api/classes/LeafData.md"
  }, {
    "text": "LeafLayout",
    "link": "/api/classes/LeafLayout.md"
  }, {
    "text": "Branch",
    "link": "/api/classes/Branch.md"
  }, {
    "text": "Leaf",
    "link": "/api/classes/Leaf.md"
  }, {
    "text": "BoundsEvent",
    "link": "/api/classes/BoundsEvent.md"
  }, {
    "text": "ChildEvent",
    "link": "/api/classes/ChildEvent.md"
  }, {
    "text": "Event",
    "link": "/api/classes/Event.md"
  }, {
    "text": "Eventer",
    "link": "/api/classes/Eventer.md"
  }, {
    "text": "ImageEvent",
    "link": "/api/classes/ImageEvent.md"
  }, {
    "text": "LayoutEvent",
    "link": "/api/classes/LayoutEvent.md"
  }, {
    "text": "LeaferEvent",
    "link": "/api/classes/LeaferEvent.md"
  }, {
    "text": "PropertyEvent",
    "link": "/api/classes/PropertyEvent.md"
  }, {
    "text": "RenderEvent",
    "link": "/api/classes/RenderEvent.md"
  }, {
    "text": "ResizeEvent",
    "link": "/api/classes/ResizeEvent.md"
  }, {
    "text": "WatchEvent",
    "link": "/api/classes/WatchEvent.md"
  }, {
    "text": "LeaferFilm",
    "link": "/api/classes/LeaferFilm.md"
  }, {
    "text": "LeaferImage",
    "link": "/api/classes/LeaferImage.md"
  }, {
    "text": "LeaferVideo",
    "link": "/api/classes/LeaferVideo.md"
  }, {
    "text": "LeafLevelList",
    "link": "/api/classes/LeafLevelList.md"
  }, {
    "text": "LeafList",
    "link": "/api/classes/LeafList.md"
  }, {
    "text": "AutoBounds",
    "link": "/api/classes/AutoBounds.md"
  }, {
    "text": "Bounds",
    "link": "/api/classes/Bounds.md"
  }, {
    "text": "Matrix",
    "link": "/api/classes/Matrix.md"
  }, {
    "text": "Point",
    "link": "/api/classes/Point.md"
  }, {
    "text": "Layouter",
    "link": "/api/classes/Layouter.md"
  }, {
    "text": "Renderer",
    "link": "/api/classes/Renderer.md"
  }, {
    "text": "Picker",
    "link": "/api/classes/Picker.md"
  }, {
    "text": "Selector",
    "link": "/api/classes/Selector.md"
  }, {
    "text": "Watcher",
    "link": "/api/classes/Watcher.md"
  }, {
    "text": "PathCreator",
    "link": "/api/classes/PathCreator.md"
  }, {
    "text": "TaskItem",
    "link": "/api/classes/TaskItem.md"
  }, {
    "text": "TaskProcessor",
    "link": "/api/classes/TaskProcessor.md"
  }, {
    "text": "App",
    "link": "/api/classes/App.md"
  }, {
    "text": "BoxData",
    "link": "/api/classes/BoxData.md"
  }, {
    "text": "CanvasData",
    "link": "/api/classes/CanvasData.md"
  }, {
    "text": "EllipseData",
    "link": "/api/classes/EllipseData.md"
  }, {
    "text": "FrameData",
    "link": "/api/classes/FrameData.md"
  }, {
    "text": "GroupData",
    "link": "/api/classes/GroupData.md"
  }, {
    "text": "ImageData",
    "link": "/api/classes/ImageData.md"
  }, {
    "text": "LeaferData",
    "link": "/api/classes/LeaferData.md"
  }, {
    "text": "LineData",
    "link": "/api/classes/LineData.md"
  }, {
    "text": "PathData",
    "link": "/api/classes/PathData.md"
  }, {
    "text": "PenData",
    "link": "/api/classes/PenData.md"
  }, {
    "text": "PolygonData",
    "link": "/api/classes/PolygonData.md"
  }, {
    "text": "RectData",
    "link": "/api/classes/RectData.md"
  }, {
    "text": "StarData",
    "link": "/api/classes/StarData.md"
  }, {
    "text": "TextData",
    "link": "/api/classes/TextData.md"
  }, {
    "text": "UIData",
    "link": "/api/classes/UIData.md"
  }, {
    "text": "Box",
    "link": "/api/classes/Box.md"
  }, {
    "text": "Canvas",
    "link": "/api/classes/Canvas.md"
  }, {
    "text": "Ellipse",
    "link": "/api/classes/Ellipse.md"
  }, {
    "text": "Frame",
    "link": "/api/classes/Frame.md"
  }, {
    "text": "Group",
    "link": "/api/classes/Group.md"
  }, {
    "text": "Image",
    "link": "/api/classes/Image.md"
  }, {
    "text": "Leafer",
    "link": "/api/classes/Leafer.md"
  }, {
    "text": "Line",
    "link": "/api/classes/Line.md"
  }, {
    "text": "Path",
    "link": "/api/classes/Path.md"
  }, {
    "text": "Pen",
    "link": "/api/classes/Pen.md"
  }, {
    "text": "Polygon",
    "link": "/api/classes/Polygon.md"
  }, {
    "text": "Rect",
    "link": "/api/classes/Rect.md"
  }, {
    "text": "Star",
    "link": "/api/classes/Star.md"
  }, {
    "text": "Text",
    "link": "/api/classes/Text.md"
  }, {
    "text": "UI",
    "link": "/api/classes/UI.md"
  }, {
    "text": "DragEvent",
    "link": "/api/classes/DragEvent.md"
  }, {
    "text": "DropEvent",
    "link": "/api/classes/DropEvent.md"
  }, {
    "text": "KeyEvent",
    "link": "/api/classes/KeyEvent.md"
  }, {
    "text": "MoveEvent",
    "link": "/api/classes/MoveEvent.md"
  }, {
    "text": "PointerEvent",
    "link": "/api/classes/PointerEvent.md"
  }, {
    "text": "RotateEvent",
    "link": "/api/classes/RotateEvent.md"
  }, {
    "text": "SwipeEvent",
    "link": "/api/classes/SwipeEvent.md"
  }, {
    "text": "TouchEvent",
    "link": "/api/classes/TouchEvent.md"
  }, {
    "text": "UIEvent",
    "link": "/api/classes/UIEvent.md"
  }, {
    "text": "ZoomEvent",
    "link": "/api/classes/ZoomEvent.md"
  }, {
    "text": "HitCanvasManager",
    "link": "/api/classes/HitCanvasManager.md"
  }, {
    "text": "Interaction",
    "link": "/api/classes/Interaction.md"
  }, {
    "text": "Cursor",
    "link": "/api/classes/Cursor.md"
  }, {
    "text": "Dragger",
    "link": "/api/classes/Dragger.md"
  }, {
    "text": "InteractionBase",
    "link": "/api/classes/InteractionBase.md"
  }],
  "collapsed": false
}, {
  "text": "Variables",
  "items": [{
    "text": "AnimateEasing",
    "link": "/api/modules.md#animateeasing"
  }, {
    "text": "PathArrowModule",
    "link": "/api/modules.md#patharrowmodule"
  }, {
    "text": "PathMatrixHelper",
    "link": "/api/modules.md#pathmatrixhelper"
  }, {
    "text": "EditDataHelper",
    "link": "/api/modules.md#editdatahelper"
  }, {
    "text": "EditSelectHelper",
    "link": "/api/modules.md#editselecthelper"
  }, {
    "text": "EditorHelper",
    "link": "/api/modules.md#editorhelper"
  }, {
    "text": "EditToolCreator",
    "link": "/api/modules.md#edittoolcreator"
  }, {
    "text": "HighBezierHelper",
    "link": "/api/modules.md#highbezierhelper"
  }, {
    "text": "HighCurveHelper",
    "link": "/api/modules.md#highcurvehelper"
  }, {
    "text": "PathScaler",
    "link": "/api/modules.md#pathscaler"
  }, {
    "text": "LeaferTypeCreator",
    "link": "/api/modules.md#leafertypecreator"
  }, {
    "text": "MultiTouchHelper",
    "link": "/api/modules.md#multitouchhelper"
  }, {
    "text": "WheelEventHelper",
    "link": "/api/modules.md#wheeleventhelper"
  }, {
    "text": "canvasSizeAttrs",
    "link": "/api/modules.md#canvassizeattrs"
  }, {
    "text": "version",
    "link": "/api/modules.md#version"
  }, {
    "text": "Plugin",
    "link": "/api/modules.md#plugin"
  }, {
    "text": "Run",
    "link": "/api/modules.md#run"
  }, {
    "text": "DataHelper",
    "link": "/api/modules.md#datahelper"
  }, {
    "text": "emptyData",
    "link": "/api/modules.md#emptydata"
  }, {
    "text": "BranchRender",
    "link": "/api/modules.md#branchrender"
  }, {
    "text": "LeafBounds",
    "link": "/api/modules.md#leafbounds"
  }, {
    "text": "LeafDataProxy",
    "link": "/api/modules.md#leafdataproxy"
  }, {
    "text": "LeafEventer",
    "link": "/api/modules.md#leafeventer"
  }, {
    "text": "LeafMatrix",
    "link": "/api/modules.md#leafmatrix"
  }, {
    "text": "LeafRender",
    "link": "/api/modules.md#leafrender"
  }, {
    "text": "BranchHelper",
    "link": "/api/modules.md#branchhelper"
  }, {
    "text": "LeafBoundsHelper",
    "link": "/api/modules.md#leafboundshelper"
  }, {
    "text": "LeafHelper",
    "link": "/api/modules.md#leafhelper"
  }, {
    "text": "WaitHelper",
    "link": "/api/modules.md#waithelper"
  }, {
    "text": "leaferTransformAttrMap",
    "link": "/api/modules.md#leafertransformattrmap"
  }, {
    "text": "extraPropertyEventMap",
    "link": "/api/modules.md#extrapropertyeventmap"
  }, {
    "text": "FileHelper",
    "link": "/api/modules.md#filehelper"
  }, {
    "text": "Resource",
    "link": "/api/modules.md#resource"
  }, {
    "text": "ImageManager",
    "link": "/api/modules.md#imagemanager"
  }, {
    "text": "AlignHelper",
    "link": "/api/modules.md#alignhelper"
  }, {
    "text": "AroundHelper",
    "link": "/api/modules.md#aroundhelper"
  }, {
    "text": "tempBounds",
    "link": "/api/modules.md#tempbounds"
  }, {
    "text": "BoundsHelper",
    "link": "/api/modules.md#boundshelper"
  }, {
    "text": "FourNumberHelper",
    "link": "/api/modules.md#fournumberhelper"
  }, {
    "text": "IncrementId",
    "link": "/api/modules.md#incrementid"
  }, {
    "text": "MathHelper",
    "link": "/api/modules.md#mathhelper"
  }, {
    "text": "OneRadian",
    "link": "/api/modules.md#oneradian"
  }, {
    "text": "PI2",
    "link": "/api/modules.md#pi2"
  }, {
    "text": "PI\\_2",
    "link": "/api/modules.md#pi_2"
  }, {
    "text": "tempMatrix",
    "link": "/api/modules.md#tempmatrix"
  }, {
    "text": "MatrixHelper",
    "link": "/api/modules.md#matrixhelper"
  }, {
    "text": "tempPoint",
    "link": "/api/modules.md#temppoint"
  }, {
    "text": "PointHelper",
    "link": "/api/modules.md#pointhelper"
  }, {
    "text": "StringNumberMap",
    "link": "/api/modules.md#stringnumbermap"
  }, {
    "text": "TwoPointBoundsHelper",
    "link": "/api/modules.md#twopointboundshelper"
  }, {
    "text": "UnitConvertHelper",
    "link": "/api/modules.md#unitconverthelper"
  }, {
    "text": "BezierHelper",
    "link": "/api/modules.md#bezierhelper"
  }, {
    "text": "EllipseHelper",
    "link": "/api/modules.md#ellipsehelper"
  }, {
    "text": "PathBounds",
    "link": "/api/modules.md#pathbounds"
  }, {
    "text": "PathCommandDataHelper",
    "link": "/api/modules.md#pathcommanddatahelper"
  }, {
    "text": "PathCommandMap",
    "link": "/api/modules.md#pathcommandmap"
  }, {
    "text": "NeedConvertToCanvasCommandMap",
    "link": "/api/modules.md#needconverttocanvascommandmap"
  }, {
    "text": "PathNumberCommandMap",
    "link": "/api/modules.md#pathnumbercommandmap"
  }, {
    "text": "PathNumberCommandLengthMap",
    "link": "/api/modules.md#pathnumbercommandlengthmap"
  }, {
    "text": "PathCommandNodeHelper",
    "link": "/api/modules.md#pathcommandnodehelper"
  }, {
    "text": "PathConvert",
    "link": "/api/modules.md#pathconvert"
  }, {
    "text": "PathCorner",
    "link": "/api/modules.md#pathcorner"
  }, {
    "text": "PathDrawer",
    "link": "/api/modules.md#pathdrawer"
  }, {
    "text": "PathHelper",
    "link": "/api/modules.md#pathhelper"
  }, {
    "text": "RectHelper",
    "link": "/api/modules.md#recthelper"
  }, {
    "text": "pen",
    "link": "/api/modules.md#pen"
  }, {
    "text": "Platform",
    "link": "/api/modules.md#platform"
  }, {
    "text": "Creator",
    "link": "/api/modules.md#creator"
  }, {
    "text": "EventCreator",
    "link": "/api/modules.md#eventcreator"
  }, {
    "text": "UICreator",
    "link": "/api/modules.md#uicreator"
  }, {
    "text": "UIBounds",
    "link": "/api/modules.md#uibounds"
  }, {
    "text": "RectRender",
    "link": "/api/modules.md#rectrender"
  }, {
    "text": "UIRender",
    "link": "/api/modules.md#uirender"
  }, {
    "text": "MyImage",
    "link": "/api/modules.md#myimage"
  }, {
    "text": "DragBoundsHelper",
    "link": "/api/modules.md#dragboundshelper"
  }, {
    "text": "MyDragEvent",
    "link": "/api/modules.md#mydragevent"
  }, {
    "text": "Keyboard",
    "link": "/api/modules.md#keyboard"
  }, {
    "text": "PointerButton",
    "link": "/api/modules.md#pointerbutton"
  }, {
    "text": "MyPointerEvent",
    "link": "/api/modules.md#mypointerevent"
  }, {
    "text": "MyTouchEvent",
    "link": "/api/modules.md#mytouchevent"
  }, {
    "text": "TextConvert",
    "link": "/api/modules.md#textconvert"
  }, {
    "text": "ColorConvert",
    "link": "/api/modules.md#colorconvert"
  }, {
    "text": "UnitConvert",
    "link": "/api/modules.md#unitconvert"
  }, {
    "text": "PathArrow",
    "link": "/api/modules.md#patharrow"
  }, {
    "text": "Paint",
    "link": "/api/modules.md#paint"
  }, {
    "text": "PaintImage",
    "link": "/api/modules.md#paintimage"
  }, {
    "text": "PaintGradient",
    "link": "/api/modules.md#paintgradient"
  }, {
    "text": "Effect",
    "link": "/api/modules.md#effect"
  }, {
    "text": "Filter",
    "link": "/api/modules.md#filter"
  }, {
    "text": "Export",
    "link": "/api/modules.md#export"
  }, {
    "text": "State",
    "link": "/api/modules.md#state"
  }, {
    "text": "Transition",
    "link": "/api/modules.md#transition"
  }, {
    "text": "InteractionHelper",
    "link": "/api/modules.md#interactionhelper"
  }],
  "collapsed": false
}, {
  "text": "Functions",
  "items": [{
    "text": "arrowType",
    "link": "/api/modules.md#arrowtype"
  }, {
    "text": "registerEditTool",
    "link": "/api/modules.md#registeredittool"
  }, {
    "text": "registerInnerEditor",
    "link": "/api/modules.md#registerinnereditor"
  }, {
    "text": "motionPathType",
    "link": "/api/modules.md#motionpathtype"
  }, {
    "text": "scaleResize",
    "link": "/api/modules.md#scaleresize"
  }, {
    "text": "scaleResizeFontSize",
    "link": "/api/modules.md#scaleresizefontsize"
  }, {
    "text": "scaleResizePath",
    "link": "/api/modules.md#scaleresizepath"
  }, {
    "text": "scaleResizePoints",
    "link": "/api/modules.md#scaleresizepoints"
  }, {
    "text": "scaleResizeGroup",
    "link": "/api/modules.md#scaleresizegroup"
  }, {
    "text": "stateType",
    "link": "/api/modules.md#statetype"
  }, {
    "text": "stateStyleType",
    "link": "/api/modules.md#statestyletype"
  }, {
    "text": "addViewport",
    "link": "/api/modules.md#addviewport"
  }, {
    "text": "addViewportConfig",
    "link": "/api/modules.md#addviewportconfig"
  }, {
    "text": "canvasPatch",
    "link": "/api/modules.md#canvaspatch"
  }, {
    "text": "useCanvas",
    "link": "/api/modules.md#usecanvas"
  }, {
    "text": "registerUI",
    "link": "/api/modules.md#registerui"
  }, {
    "text": "registerUIEvent",
    "link": "/api/modules.md#registeruievent"
  }, {
    "text": "decorateLeafAttr",
    "link": "/api/modules.md#decorateleafattr"
  }, {
    "text": "attr",
    "link": "/api/modules.md#attr"
  }, {
    "text": "defineLeafAttr",
    "link": "/api/modules.md#defineleafattr"
  }, {
    "text": "dataType",
    "link": "/api/modules.md#datatype"
  }, {
    "text": "positionType",
    "link": "/api/modules.md#positiontype"
  }, {
    "text": "scrollType",
    "link": "/api/modules.md#scrolltype"
  }, {
    "text": "autoLayoutType",
    "link": "/api/modules.md#autolayouttype"
  }, {
    "text": "scaleType",
    "link": "/api/modules.md#scaletype"
  }, {
    "text": "rotationType",
    "link": "/api/modules.md#rotationtype"
  }, {
    "text": "boundsType",
    "link": "/api/modules.md#boundstype"
  }, {
    "text": "naturalBoundsType",
    "link": "/api/modules.md#naturalboundstype"
  }, {
    "text": "doBoundsType",
    "link": "/api/modules.md#doboundstype"
  }, {
    "text": "pathInputType",
    "link": "/api/modules.md#pathinputtype"
  }, {
    "text": "pathType",
    "link": "/api/modules.md#pathtype"
  }, {
    "text": "affectStrokeBoundsType",
    "link": "/api/modules.md#affectstrokeboundstype"
  }, {
    "text": "doStrokeType",
    "link": "/api/modules.md#dostroketype"
  }, {
    "text": "strokeType",
    "link": "/api/modules.md#stroketype"
  }, {
    "text": "affectRenderBoundsType",
    "link": "/api/modules.md#affectrenderboundstype"
  }, {
    "text": "surfaceType",
    "link": "/api/modules.md#surfacetype"
  }, {
    "text": "dimType",
    "link": "/api/modules.md#dimtype"
  }, {
    "text": "opacityType",
    "link": "/api/modules.md#opacitytype"
  }, {
    "text": "visibleType",
    "link": "/api/modules.md#visibletype"
  }, {
    "text": "sortType",
    "link": "/api/modules.md#sorttype"
  }, {
    "text": "maskType",
    "link": "/api/modules.md#masktype"
  }, {
    "text": "eraserType",
    "link": "/api/modules.md#erasertype"
  }, {
    "text": "hitType",
    "link": "/api/modules.md#hittype"
  }, {
    "text": "cursorType",
    "link": "/api/modules.md#cursortype"
  }, {
    "text": "dataProcessor",
    "link": "/api/modules.md#dataprocessor"
  }, {
    "text": "layoutProcessor",
    "link": "/api/modules.md#layoutprocessor"
  }, {
    "text": "defineDataProcessor",
    "link": "/api/modules.md#definedataprocessor"
  }, {
    "text": "defineKey",
    "link": "/api/modules.md#definekey"
  }, {
    "text": "getDescriptor",
    "link": "/api/modules.md#getdescriptor"
  }, {
    "text": "createDescriptor",
    "link": "/api/modules.md#createdescriptor"
  }, {
    "text": "rewrite",
    "link": "/api/modules.md#rewrite"
  }, {
    "text": "rewriteAble",
    "link": "/api/modules.md#rewriteable"
  }, {
    "text": "useModule",
    "link": "/api/modules.md#usemodule"
  }, {
    "text": "isUndefined",
    "link": "/api/modules.md#isundefined"
  }, {
    "text": "isNull",
    "link": "/api/modules.md#isnull"
  }, {
    "text": "isString",
    "link": "/api/modules.md#isstring"
  }, {
    "text": "isFinite",
    "link": "/api/modules.md#isfinite"
  }, {
    "text": "isNumber",
    "link": "/api/modules.md#isnumber"
  }, {
    "text": "tryToNumber",
    "link": "/api/modules.md#trytonumber"
  }, {
    "text": "isArray",
    "link": "/api/modules.md#isarray"
  }, {
    "text": "isObject",
    "link": "/api/modules.md#isobject"
  }, {
    "text": "isData",
    "link": "/api/modules.md#isdata"
  }, {
    "text": "isEmptyData",
    "link": "/api/modules.md#isemptydata"
  }, {
    "text": "getPointData",
    "link": "/api/modules.md#getpointdata"
  }, {
    "text": "getBoundsData",
    "link": "/api/modules.md#getboundsdata"
  }, {
    "text": "path",
    "link": "/api/modules.md#path"
  }, {
    "text": "effectType",
    "link": "/api/modules.md#effecttype"
  }, {
    "text": "resizeType",
    "link": "/api/modules.md#resizetype"
  }, {
    "text": "zoomLayerType",
    "link": "/api/modules.md#zoomlayertype"
  }, {
    "text": "createAttr",
    "link": "/api/modules.md#createattr"
  }],
  "collapsed": false
}, {
  "text": "Types",
  "items": [{
    "text": "IInnerEditorMode",
    "link": "/api/modules.md#iinnereditormode"
  }, {
    "text": "IScrollBarTheme",
    "link": "/api/modules.md#iscrollbartheme"
  }, {
    "text": "ITransition",
    "link": "/api/modules.md#itransition"
  }, {
    "text": "IAnimateEasing",
    "link": "/api/modules.md#ianimateeasing"
  }, {
    "text": "IAnimateEasingName",
    "link": "/api/modules.md#ianimateeasingname"
  }, {
    "text": "IAnimateEnding",
    "link": "/api/modules.md#ianimateending"
  }, {
    "text": "ILeaferType",
    "link": "/api/modules.md#ileafertype"
  }, {
    "text": "ILeaferMode",
    "link": "/api/modules.md#ileafermode"
  }, {
    "text": "IZoomType",
    "link": "/api/modules.md#izoomtype"
  }, {
    "text": "IWindingRule",
    "link": "/api/modules.md#iwindingrule"
  }, {
    "text": "ICanvasPattern",
    "link": "/api/modules.md#icanvaspattern"
  }, {
    "text": "ICanvasContext2DSettings",
    "link": "/api/modules.md#icanvascontext2dsettings"
  }, {
    "text": "IHitCanvasConfig",
    "link": "/api/modules.md#ihitcanvasconfig"
  }, {
    "text": "ILeaferCanvasView",
    "link": "/api/modules.md#ileafercanvasview"
  }, {
    "text": "ICanvasSizeAttr",
    "link": "/api/modules.md#icanvassizeattr"
  }, {
    "text": "IBlob",
    "link": "/api/modules.md#iblob"
  }, {
    "text": "ICanvasType",
    "link": "/api/modules.md#icanvastype"
  }, {
    "text": "INumber",
    "link": "/api/modules.md#inumber"
  }, {
    "text": "IBoolean",
    "link": "/api/modules.md#iboolean"
  }, {
    "text": "IString",
    "link": "/api/modules.md#istring"
  }, {
    "text": "IValue",
    "link": "/api/modules.md#ivalue"
  }, {
    "text": "ITimer",
    "link": "/api/modules.md#itimer"
  }, {
    "text": "IPathString",
    "link": "/api/modules.md#ipathstring"
  }, {
    "text": "IFourNumber",
    "link": "/api/modules.md#ifournumber"
  }, {
    "text": "ILeafListItemCallback",
    "link": "/api/modules.md#ileaflistitemcallback"
  }, {
    "text": "ISide",
    "link": "/api/modules.md#iside"
  }, {
    "text": "IAxis",
    "link": "/api/modules.md#iaxis"
  }, {
    "text": "IAxisReverse",
    "link": "/api/modules.md#iaxisreverse"
  }, {
    "text": "IFlowType",
    "link": "/api/modules.md#iflowtype"
  }, {
    "text": "IFlowBoxType",
    "link": "/api/modules.md#iflowboxtype"
  }, {
    "text": "IGap",
    "link": "/api/modules.md#igap"
  }, {
    "text": "IAxisAlign",
    "link": "/api/modules.md#iaxisalign"
  }, {
    "text": "IFlowWrap",
    "link": "/api/modules.md#iflowwrap"
  }, {
    "text": "IAutoSize",
    "link": "/api/modules.md#iautosize"
  }, {
    "text": "IConstraintType",
    "link": "/api/modules.md#iconstrainttype"
  }, {
    "text": "IScaleFixed",
    "link": "/api/modules.md#iscalefixed"
  }, {
    "text": "IHitType",
    "link": "/api/modules.md#ihittype"
  }, {
    "text": "IMaskType",
    "link": "/api/modules.md#imasktype"
  }, {
    "text": "IEraserType",
    "link": "/api/modules.md#ierasertype"
  }, {
    "text": "IBlendMode",
    "link": "/api/modules.md#iblendmode"
  }, {
    "text": "IEditSize",
    "link": "/api/modules.md#ieditsize"
  }, {
    "text": "IDragBoundsType",
    "link": "/api/modules.md#idragboundstype"
  }, {
    "text": "IDirection",
    "link": "/api/modules.md#idirection"
  }, {
    "text": "IDirection4",
    "link": "/api/modules.md#idirection4"
  }, {
    "text": "IAlign",
    "link": "/api/modules.md#ialign"
  }, {
    "text": "IBaseLineAlign",
    "link": "/api/modules.md#ibaselinealign"
  }, {
    "text": "IFlowAlign",
    "link": "/api/modules.md#iflowalign"
  }, {
    "text": "IAround",
    "link": "/api/modules.md#iaround"
  }, {
    "text": "ICursorType",
    "link": "/api/modules.md#icursortype"
  }, {
    "text": "IStateStyleType",
    "link": "/api/modules.md#istatestyletype"
  }, {
    "text": "ILeafAttrDescriptor",
    "link": "/api/modules.md#ileafattrdescriptor"
  }, {
    "text": "IBranchRenderModule",
    "link": "/api/modules.md#ibranchrendermodule"
  }, {
    "text": "ILeafBoundsModule",
    "link": "/api/modules.md#ileafboundsmodule"
  }, {
    "text": "ILeafDataProxyModule",
    "link": "/api/modules.md#ileafdataproxymodule"
  }, {
    "text": "ILeafEventerModule",
    "link": "/api/modules.md#ileafeventermodule"
  }, {
    "text": "ILeafHitModule",
    "link": "/api/modules.md#ileafhitmodule"
  }, {
    "text": "ILeafMatrixModule",
    "link": "/api/modules.md#ileafmatrixmodule"
  }, {
    "text": "ILeafRenderModule",
    "link": "/api/modules.md#ileafrendermodule"
  }, {
    "text": "IGestureType",
    "link": "/api/modules.md#igesturetype"
  }, {
    "text": "IEventListener",
    "link": "/api/modules.md#ieventlistener"
  }, {
    "text": "IEventOption",
    "link": "/api/modules.md#ieventoption"
  }, {
    "text": "IEventParams",
    "link": "/api/modules.md#ieventparams"
  }, {
    "text": "InnerId",
    "link": "/api/modules.md#innerid"
  }, {
    "text": "PointerType",
    "link": "/api/modules.md#pointertype"
  }, {
    "text": "IShortcutKeys",
    "link": "/api/modules.md#ishortcutkeys"
  }, {
    "text": "IShortcutKeyCodes",
    "link": "/api/modules.md#ishortcutkeycodes"
  }, {
    "text": "IKeyCodes",
    "link": "/api/modules.md#ikeycodes"
  }, {
    "text": "IExportImageType",
    "link": "/api/modules.md#iexportimagetype"
  }, {
    "text": "IExportFileType",
    "link": "/api/modules.md#iexportfiletype"
  }, {
    "text": "IFilmFileType",
    "link": "/api/modules.md#ifilmfiletype"
  }, {
    "text": "IVideoFileType",
    "link": "/api/modules.md#ivideofiletype"
  }, {
    "text": "IMultimediaType",
    "link": "/api/modules.md#imultimediatype"
  }, {
    "text": "IResponseType",
    "link": "/api/modules.md#iresponsetype"
  }, {
    "text": "ILocationType",
    "link": "/api/modules.md#ilocationtype"
  }, {
    "text": "IBoundsType",
    "link": "/api/modules.md#iboundstype"
  }, {
    "text": "ILayoutAttr",
    "link": "/api/modules.md#ilayoutattr"
  }, {
    "text": "MCommandData",
    "link": "/api/modules.md#mcommanddata"
  }, {
    "text": "HCommandData",
    "link": "/api/modules.md#hcommanddata"
  }, {
    "text": "VCommandData",
    "link": "/api/modules.md#vcommanddata"
  }, {
    "text": "LCommandData",
    "link": "/api/modules.md#lcommanddata"
  }, {
    "text": "CCommandData",
    "link": "/api/modules.md#ccommanddata"
  }, {
    "text": "SCommandData",
    "link": "/api/modules.md#scommanddata"
  }, {
    "text": "QCommandData",
    "link": "/api/modules.md#qcommanddata"
  }, {
    "text": "TCommandData",
    "link": "/api/modules.md#tcommanddata"
  }, {
    "text": "ZCommandData",
    "link": "/api/modules.md#zcommanddata"
  }, {
    "text": "ACommandData",
    "link": "/api/modules.md#acommanddata"
  }, {
    "text": "RectCommandData",
    "link": "/api/modules.md#rectcommanddata"
  }, {
    "text": "RoundRectCommandData",
    "link": "/api/modules.md#roundrectcommanddata"
  }, {
    "text": "EllipseCommandData",
    "link": "/api/modules.md#ellipsecommanddata"
  }, {
    "text": "ArcCommandData",
    "link": "/api/modules.md#arccommanddata"
  }, {
    "text": "ArcToCommandData",
    "link": "/api/modules.md#arctocommanddata"
  }, {
    "text": "CanvasPathCommand",
    "link": "/api/modules.md#canvaspathcommand"
  }, {
    "text": "IPathCommandData",
    "link": "/api/modules.md#ipathcommanddata"
  }, {
    "text": "IPathCommandObject",
    "link": "/api/modules.md#ipathcommandobject"
  }, {
    "text": "IPathCommandNode",
    "link": "/api/modules.md#ipathcommandnode"
  }, {
    "text": "PathNodeHandleName",
    "link": "/api/modules.md#pathnodehandlename"
  }, {
    "text": "IImageCrossOrigin",
    "link": "/api/modules.md#iimagecrossorigin"
  }, {
    "text": "IAnswer",
    "link": "/api/modules.md#ianswer"
  }, {
    "text": "IAnimation",
    "link": "/api/modules.md#ianimation"
  }, {
    "text": "IAnimateType",
    "link": "/api/modules.md#ianimatetype"
  }, {
    "text": "IKeyframe",
    "link": "/api/modules.md#ikeyframe"
  }, {
    "text": "IKeyframeId",
    "link": "/api/modules.md#ikeyframeid"
  }, {
    "text": "IScrollTheme",
    "link": "/api/modules.md#iscrolltheme"
  }, {
    "text": "ILinkerPointType",
    "link": "/api/modules.md#ilinkerpointtype"
  }, {
    "text": "IRobotActionName",
    "link": "/api/modules.md#irobotactionname"
  }, {
    "text": "IStateName",
    "link": "/api/modules.md#istatename"
  }, {
    "text": "IUITag",
    "link": "/api/modules.md#iuitag"
  }, {
    "text": "IEditorEditInnerData",
    "link": "/api/modules.md#ieditoreditinnerdata"
  }, {
    "text": "IEditPointType",
    "link": "/api/modules.md#ieditpointtype"
  }, {
    "text": "IUIBoundsModule",
    "link": "/api/modules.md#iuiboundsmodule"
  }, {
    "text": "IUIHitModule",
    "link": "/api/modules.md#iuihitmodule"
  }, {
    "text": "IUIRenderModule",
    "link": "/api/modules.md#iuirendermodule"
  }, {
    "text": "IRectRenderModule",
    "link": "/api/modules.md#irectrendermodule"
  }, {
    "text": "IImageRenderModule",
    "link": "/api/modules.md#iimagerendermodule"
  }, {
    "text": "ITextRenderModule",
    "link": "/api/modules.md#itextrendermodule"
  }, {
    "text": "IGroupRenderModule",
    "link": "/api/modules.md#igrouprendermodule"
  }, {
    "text": "IFrameRenderModule",
    "link": "/api/modules.md#iframerendermodule"
  }, {
    "text": "ILeafPaintColor",
    "link": "/api/modules.md#ileafpaintcolor"
  }, {
    "text": "ILeafFill",
    "link": "/api/modules.md#ileaffill"
  }, {
    "text": "IPercent",
    "link": "/api/modules.md#ipercent"
  }, {
    "text": "IColorString",
    "link": "/api/modules.md#icolorstring"
  }, {
    "text": "ICornerRadiusString",
    "link": "/api/modules.md#icornerradiusstring"
  }, {
    "text": "IStrokeWidthString",
    "link": "/api/modules.md#istrokewidthstring"
  }, {
    "text": "IDashPatternString",
    "link": "/api/modules.md#idashpatternstring"
  }, {
    "text": "IPaintString",
    "link": "/api/modules.md#ipaintstring"
  }, {
    "text": "IShadowString",
    "link": "/api/modules.md#ishadowstring"
  }, {
    "text": "IPaint",
    "link": "/api/modules.md#ipaint"
  }, {
    "text": "IStrokePaint",
    "link": "/api/modules.md#istrokepaint"
  }, {
    "text": "IFill",
    "link": "/api/modules.md#ifill"
  }, {
    "text": "IStroke",
    "link": "/api/modules.md#istroke"
  }, {
    "text": "IPaintAttr",
    "link": "/api/modules.md#ipaintattr"
  }, {
    "text": "IPaintType",
    "link": "/api/modules.md#ipainttype"
  }, {
    "text": "IGradientType",
    "link": "/api/modules.md#igradienttype"
  }, {
    "text": "IColor",
    "link": "/api/modules.md#icolor"
  }, {
    "text": "IImageFilterType",
    "link": "/api/modules.md#iimagefiltertype"
  }, {
    "text": "IImageFilters",
    "link": "/api/modules.md#iimagefilters"
  }, {
    "text": "IImagePaintMode",
    "link": "/api/modules.md#iimagepaintmode"
  }, {
    "text": "IRepeat",
    "link": "/api/modules.md#irepeat"
  }, {
    "text": "IStrokeAlign",
    "link": "/api/modules.md#istrokealign"
  }, {
    "text": "IStrokeCap",
    "link": "/api/modules.md#istrokecap"
  }, {
    "text": "IStrokeJoin",
    "link": "/api/modules.md#istrokejoin"
  }, {
    "text": "IArrowType",
    "link": "/api/modules.md#iarrowtype"
  }, {
    "text": "IArrowStyle",
    "link": "/api/modules.md#iarrowstyle"
  }, {
    "text": "ITextAlign",
    "link": "/api/modules.md#itextalign"
  }, {
    "text": "IVerticalAlign",
    "link": "/api/modules.md#iverticalalign"
  }, {
    "text": "ITextCase",
    "link": "/api/modules.md#itextcase"
  }, {
    "text": "IFontWeight",
    "link": "/api/modules.md#ifontweight"
  }, {
    "text": "IFontWeightNumer",
    "link": "/api/modules.md#ifontweightnumer"
  }, {
    "text": "IFontWeightString",
    "link": "/api/modules.md#ifontweightstring"
  }, {
    "text": "ITextDecoration",
    "link": "/api/modules.md#itextdecoration"
  }, {
    "text": "ITextDecorationType",
    "link": "/api/modules.md#itextdecorationtype"
  }, {
    "text": "ITextWrap",
    "link": "/api/modules.md#itextwrap"
  }, {
    "text": "IWritingMode",
    "link": "/api/modules.md#iwritingmode"
  }, {
    "text": "IOverflow",
    "link": "/api/modules.md#ioverflow"
  }, {
    "text": "ITextOverflow",
    "link": "/api/modules.md#itextoverflow"
  }],
  "collapsed": false
}, {
  "text": "Enumerations",
  "items": [{
    "text": "Answer",
    "link": "/api/enums/Answer.md"
  }, {
    "text": "PathNodeHandleType",
    "link": "/api/enums/PathNodeHandleType.md"
  }, {
    "text": "Direction4",
    "link": "/api/enums/Direction4.md"
  }, {
    "text": "Direction9",
    "link": "/api/enums/Direction9.md"
  }],
  "collapsed": false
}, {
  "text": "Interfaces",
  "items": [{
    "text": "IEditBox",
    "link": "/api/interfaces/IEditBox.md"
  }, {
    "text": "IEditSelect",
    "link": "/api/interfaces/IEditSelect.md"
  }, {
    "text": "IEditor",
    "link": "/api/interfaces/IEditor.md"
  }, {
    "text": "IEditTool",
    "link": "/api/interfaces/IEditTool.md"
  }, {
    "text": "IInnerEditor",
    "link": "/api/interfaces/IInnerEditor.md"
  }, {
    "text": "IEditorEvent",
    "link": "/api/interfaces/IEditorEvent.md"
  }, {
    "text": "IInnerEditorEvent",
    "link": "/api/interfaces/IInnerEditorEvent.md"
  }, {
    "text": "IEditorGroupEvent",
    "link": "/api/interfaces/IEditorGroupEvent.md"
  }, {
    "text": "IEditorMoveEvent",
    "link": "/api/interfaces/IEditorMoveEvent.md"
  }, {
    "text": "IEditorScaleEvent",
    "link": "/api/interfaces/IEditorScaleEvent.md"
  }, {
    "text": "IEditorRotateEvent",
    "link": "/api/interfaces/IEditorRotateEvent.md"
  }, {
    "text": "IEditorSkewEvent",
    "link": "/api/interfaces/IEditorSkewEvent.md"
  }, {
    "text": "ISelectArea",
    "link": "/api/interfaces/ISelectArea.md"
  }, {
    "text": "ISimulateElement",
    "link": "/api/interfaces/ISimulateElement.md"
  }, {
    "text": "IStroker",
    "link": "/api/interfaces/IStroker.md"
  }, {
    "text": "IFlowWrapDrawData",
    "link": "/api/interfaces/IFlowWrapDrawData.md"
  }, {
    "text": "IFlowDrawData",
    "link": "/api/interfaces/IFlowDrawData.md"
  }, {
    "text": "IGapBoundsData",
    "link": "/api/interfaces/IGapBoundsData.md"
  }, {
    "text": "IFlowAlignToAxisAlignMap",
    "link": "/api/interfaces/IFlowAlignToAxisAlignMap.md"
  }, {
    "text": "IFlowParseData",
    "link": "/api/interfaces/IFlowParseData.md"
  }, {
    "text": "IHTMLTextData",
    "link": "/api/interfaces/IHTMLTextData.md"
  }, {
    "text": "IHTMLTextInputData",
    "link": "/api/interfaces/IHTMLTextInputData.md"
  }, {
    "text": "IScrollBarConfig",
    "link": "/api/interfaces/IScrollBarConfig.md"
  }, {
    "text": "IScrollBar",
    "link": "/api/interfaces/IScrollBar.md"
  }, {
    "text": "IAnimateOptions",
    "link": "/api/interfaces/IAnimateOptions.md"
  }, {
    "text": "IAnimateEasingFunction",
    "link": "/api/interfaces/IAnimateEasingFunction.md"
  }, {
    "text": "ICustomEasingFunction",
    "link": "/api/interfaces/ICustomEasingFunction.md"
  }, {
    "text": "ICubicBezierEasing",
    "link": "/api/interfaces/ICubicBezierEasing.md"
  }, {
    "text": "IStepsEasing",
    "link": "/api/interfaces/IStepsEasing.md"
  }, {
    "text": "IAnimateEvents",
    "link": "/api/interfaces/IAnimateEvents.md"
  }, {
    "text": "IAnimateEventFunction",
    "link": "/api/interfaces/IAnimateEventFunction.md"
  }, {
    "text": "IAppBase",
    "link": "/api/interfaces/IAppBase.md"
  }, {
    "text": "ILeaferConfig",
    "link": "/api/interfaces/ILeaferConfig.md"
  }, {
    "text": "ILeaferAttrData",
    "link": "/api/interfaces/ILeaferAttrData.md"
  }, {
    "text": "IZoomOptions",
    "link": "/api/interfaces/IZoomOptions.md"
  }, {
    "text": "ILeaferBase",
    "link": "/api/interfaces/ILeaferBase.md"
  }, {
    "text": "ILeaferTypeCreator",
    "link": "/api/interfaces/ILeaferTypeCreator.md"
  }, {
    "text": "ILeaferTypeFunction",
    "link": "/api/interfaces/ILeaferTypeFunction.md"
  }, {
    "text": "ILeaferTypeList",
    "link": "/api/interfaces/ILeaferTypeList.md"
  }, {
    "text": "ICreator",
    "link": "/api/interfaces/ICreator.md"
  }, {
    "text": "IUICreator",
    "link": "/api/interfaces/IUICreator.md"
  }, {
    "text": "IPath2D",
    "link": "/api/interfaces/IPath2D.md"
  }, {
    "text": "ICanvasContext2D",
    "link": "/api/interfaces/ICanvasContext2D.md"
  }, {
    "text": "ITextMetrics",
    "link": "/api/interfaces/ITextMetrics.md"
  }, {
    "text": "ICanvasManager",
    "link": "/api/interfaces/ICanvasManager.md"
  }, {
    "text": "IHitCanvasManager",
    "link": "/api/interfaces/IHitCanvasManager.md"
  }, {
    "text": "ILeaferCanvasConfig",
    "link": "/api/interfaces/ILeaferCanvasConfig.md"
  }, {
    "text": "ICanvasStrokeOptions",
    "link": "/api/interfaces/ICanvasStrokeOptions.md"
  }, {
    "text": "ICanvasCacheOptions",
    "link": "/api/interfaces/ICanvasCacheOptions.md"
  }, {
    "text": "ICanvasAttr",
    "link": "/api/interfaces/ICanvasAttr.md"
  }, {
    "text": "ILeaferCanvas",
    "link": "/api/interfaces/ILeaferCanvas.md"
  }, {
    "text": "IHitCanvas",
    "link": "/api/interfaces/IHitCanvas.md"
  }, {
    "text": "IWindingRuleData",
    "link": "/api/interfaces/IWindingRuleData.md"
  }, {
    "text": "IBlobFunction",
    "link": "/api/interfaces/IBlobFunction.md"
  }, {
    "text": "ISkiaCanvas",
    "link": "/api/interfaces/ISkiaCanvas.md"
  }, {
    "text": "ISkiaCanvasExportConfig",
    "link": "/api/interfaces/ISkiaCanvasExportConfig.md"
  }, {
    "text": "ISkiaNAPICanvas",
    "link": "/api/interfaces/ISkiaNAPICanvas.md"
  }, {
    "text": "IControl",
    "link": "/api/interfaces/IControl.md"
  }, {
    "text": "IObject",
    "link": "/api/interfaces/IObject.md"
  }, {
    "text": "IBooleanMap",
    "link": "/api/interfaces/IBooleanMap.md"
  }, {
    "text": "INumberMap",
    "link": "/api/interfaces/INumberMap.md"
  }, {
    "text": "IStringMap",
    "link": "/api/interfaces/IStringMap.md"
  }, {
    "text": "IFunctionMap",
    "link": "/api/interfaces/IFunctionMap.md"
  }, {
    "text": "IPointDataMap",
    "link": "/api/interfaces/IPointDataMap.md"
  }, {
    "text": "IDataTypeHandle",
    "link": "/api/interfaces/IDataTypeHandle.md"
  }, {
    "text": "IDataProcessor",
    "link": "/api/interfaces/IDataProcessor.md"
  }, {
    "text": "ILeafDataOptions",
    "link": "/api/interfaces/ILeafDataOptions.md"
  }, {
    "text": "ILeafData",
    "link": "/api/interfaces/ILeafData.md"
  }, {
    "text": "ILeafMap",
    "link": "/api/interfaces/ILeafMap.md"
  }, {
    "text": "ILeafArrayMap",
    "link": "/api/interfaces/ILeafArrayMap.md"
  }, {
    "text": "ILeafList",
    "link": "/api/interfaces/ILeafList.md"
  }, {
    "text": "ILeafLevelList",
    "link": "/api/interfaces/ILeafLevelList.md"
  }, {
    "text": "IBranch",
    "link": "/api/interfaces/IBranch.md"
  }, {
    "text": "IPointGap",
    "link": "/api/interfaces/IPointGap.md"
  }, {
    "text": "IFlowAxisAlign",
    "link": "/api/interfaces/IFlowAxisAlign.md"
  }, {
    "text": "IRangeSize",
    "link": "/api/interfaces/IRangeSize.md"
  }, {
    "text": "IInterlace",
    "link": "/api/interfaces/IInterlace.md"
  }, {
    "text": "IUnitData",
    "link": "/api/interfaces/IUnitData.md"
  }, {
    "text": "IPercentData",
    "link": "/api/interfaces/IPercentData.md"
  }, {
    "text": "IConstraint",
    "link": "/api/interfaces/IConstraint.md"
  }, {
    "text": "IImageCursor",
    "link": "/api/interfaces/IImageCursor.md"
  }, {
    "text": "IFilter",
    "link": "/api/interfaces/IFilter.md"
  }, {
    "text": "ILeafAttrData",
    "link": "/api/interfaces/ILeafAttrData.md"
  }, {
    "text": "ILeafInputData",
    "link": "/api/interfaces/ILeafInputData.md"
  }, {
    "text": "ILeafComputedData",
    "link": "/api/interfaces/ILeafComputedData.md"
  }, {
    "text": "IArrowPathData",
    "link": "/api/interfaces/IArrowPathData.md"
  }, {
    "text": "ILeaf",
    "link": "/api/interfaces/ILeaf.md"
  }, {
    "text": "ILeafAttrDescriptorFn",
    "link": "/api/interfaces/ILeafAttrDescriptorFn.md"
  }, {
    "text": "ICachedLeaf",
    "link": "/api/interfaces/ICachedLeaf.md"
  }, {
    "text": "ILeafComplexCachedData",
    "link": "/api/interfaces/ILeafComplexCachedData.md"
  }, {
    "text": "IZoomView",
    "link": "/api/interfaces/IZoomView.md"
  }, {
    "text": "IBranchRender",
    "link": "/api/interfaces/IBranchRender.md"
  }, {
    "text": "ILeafBounds",
    "link": "/api/interfaces/ILeafBounds.md"
  }, {
    "text": "ILeafDataProxy",
    "link": "/api/interfaces/ILeafDataProxy.md"
  }, {
    "text": "ILeafEventer",
    "link": "/api/interfaces/ILeafEventer.md"
  }, {
    "text": "ILeafHit",
    "link": "/api/interfaces/ILeafHit.md"
  }, {
    "text": "ILeafMatrix",
    "link": "/api/interfaces/ILeafMatrix.md"
  }, {
    "text": "ILeafRender",
    "link": "/api/interfaces/ILeafRender.md"
  }, {
    "text": "IEvent",
    "link": "/api/interfaces/IEvent.md"
  }, {
    "text": "IEventTarget",
    "link": "/api/interfaces/IEventTarget.md"
  }, {
    "text": "ILeaferEvent",
    "link": "/api/interfaces/ILeaferEvent.md"
  }, {
    "text": "IRenderEvent",
    "link": "/api/interfaces/IRenderEvent.md"
  }, {
    "text": "IAnimateEvent",
    "link": "/api/interfaces/IAnimateEvent.md"
  }, {
    "text": "IChildEvent",
    "link": "/api/interfaces/IChildEvent.md"
  }, {
    "text": "IBoundsEvent",
    "link": "/api/interfaces/IBoundsEvent.md"
  }, {
    "text": "IResizeEvent",
    "link": "/api/interfaces/IResizeEvent.md"
  }, {
    "text": "IResizeEventListener",
    "link": "/api/interfaces/IResizeEventListener.md"
  }, {
    "text": "IUpdateEvent",
    "link": "/api/interfaces/IUpdateEvent.md"
  }, {
    "text": "IPropertyEvent",
    "link": "/api/interfaces/IPropertyEvent.md"
  }, {
    "text": "ILayoutEvent",
    "link": "/api/interfaces/ILayoutEvent.md"
  }, {
    "text": "IWatchEvent",
    "link": "/api/interfaces/IWatchEvent.md"
  }, {
    "text": "IMultiTouchData",
    "link": "/api/interfaces/IMultiTouchData.md"
  }, {
    "text": "IKeepTouchData",
    "link": "/api/interfaces/IKeepTouchData.md"
  }, {
    "text": "IEventListenerOptions",
    "link": "/api/interfaces/IEventListenerOptions.md"
  }, {
    "text": "IEventListenerItem",
    "link": "/api/interfaces/IEventListenerItem.md"
  }, {
    "text": "IEventListenerMap",
    "link": "/api/interfaces/IEventListenerMap.md"
  }, {
    "text": "IEventParamsMap",
    "link": "/api/interfaces/IEventParamsMap.md"
  }, {
    "text": "IEventListenerId",
    "link": "/api/interfaces/IEventListenerId.md"
  }, {
    "text": "IEventer",
    "link": "/api/interfaces/IEventer.md"
  }, {
    "text": "IProgressData",
    "link": "/api/interfaces/IProgressData.md"
  }, {
    "text": "IProgressFunction",
    "link": "/api/interfaces/IProgressFunction.md"
  }, {
    "text": "IUIEvent",
    "link": "/api/interfaces/IUIEvent.md"
  }, {
    "text": "IPointerEvent",
    "link": "/api/interfaces/IPointerEvent.md"
  }, {
    "text": "ITouchEvent",
    "link": "/api/interfaces/ITouchEvent.md"
  }, {
    "text": "IDragEvent",
    "link": "/api/interfaces/IDragEvent.md"
  }, {
    "text": "IDropEvent",
    "link": "/api/interfaces/IDropEvent.md"
  }, {
    "text": "IRotateEvent",
    "link": "/api/interfaces/IRotateEvent.md"
  }, {
    "text": "IZoomEvent",
    "link": "/api/interfaces/IZoomEvent.md"
  }, {
    "text": "IMoveEvent",
    "link": "/api/interfaces/IMoveEvent.md"
  }, {
    "text": "IWheelEvent",
    "link": "/api/interfaces/IWheelEvent.md"
  }, {
    "text": "ISwipeEvent",
    "link": "/api/interfaces/ISwipeEvent.md"
  }, {
    "text": "IKeyEvent",
    "link": "/api/interfaces/IKeyEvent.md"
  }, {
    "text": "IShortcutKeysCheck",
    "link": "/api/interfaces/IShortcutKeysCheck.md"
  }, {
    "text": "IImageEvent",
    "link": "/api/interfaces/IImageEvent.md"
  }, {
    "text": "IExportOptions",
    "link": "/api/interfaces/IExportOptions.md"
  }, {
    "text": "IJSONOptions",
    "link": "/api/interfaces/IJSONOptions.md"
  }, {
    "text": "IExportResult",
    "link": "/api/interfaces/IExportResult.md"
  }, {
    "text": "IExportResultFunction",
    "link": "/api/interfaces/IExportResultFunction.md"
  }, {
    "text": "IExportOnCanvasFunction",
    "link": "/api/interfaces/IExportOnCanvasFunction.md"
  }, {
    "text": "IResource",
    "link": "/api/interfaces/IResource.md"
  }, {
    "text": "IFunction",
    "link": "/api/interfaces/IFunction.md"
  }, {
    "text": "INumberFunction",
    "link": "/api/interfaces/INumberFunction.md"
  }, {
    "text": "IStringFunction",
    "link": "/api/interfaces/IStringFunction.md"
  }, {
    "text": "IObjectFunction",
    "link": "/api/interfaces/IObjectFunction.md"
  }, {
    "text": "IValueFunction",
    "link": "/api/interfaces/IValueFunction.md"
  }, {
    "text": "IPointDataFunction",
    "link": "/api/interfaces/IPointDataFunction.md"
  }, {
    "text": "IAttrDecorator",
    "link": "/api/interfaces/IAttrDecorator.md"
  }, {
    "text": "IImageManager",
    "link": "/api/interfaces/IImageManager.md"
  }, {
    "text": "ILeaferFilmConfig",
    "link": "/api/interfaces/ILeaferFilmConfig.md"
  }, {
    "text": "ILeaferFilm",
    "link": "/api/interfaces/ILeaferFilm.md"
  }, {
    "text": "IFilmDecoder",
    "link": "/api/interfaces/IFilmDecoder.md"
  }, {
    "text": "IFilmFrame",
    "link": "/api/interfaces/IFilmFrame.md"
  }, {
    "text": "IFilmOptions",
    "link": "/api/interfaces/IFilmOptions.md"
  }, {
    "text": "IFilmPlayOptions",
    "link": "/api/interfaces/IFilmPlayOptions.md"
  }, {
    "text": "ILeaferImageConfig",
    "link": "/api/interfaces/ILeaferImageConfig.md"
  }, {
    "text": "IImageLOD",
    "link": "/api/interfaces/IImageLOD.md"
  }, {
    "text": "IImageTileLOD",
    "link": "/api/interfaces/IImageTileLOD.md"
  }, {
    "text": "ILeaferImageOnLoaded",
    "link": "/api/interfaces/ILeaferImageOnLoaded.md"
  }, {
    "text": "ILeaferImageOnError",
    "link": "/api/interfaces/ILeaferImageOnError.md"
  }, {
    "text": "ILeaferImageCacheCanvas",
    "link": "/api/interfaces/ILeaferImageCacheCanvas.md"
  }, {
    "text": "ILeaferImagePatternPaint",
    "link": "/api/interfaces/ILeaferImagePatternPaint.md"
  }, {
    "text": "ILeaferImageSliceData",
    "link": "/api/interfaces/ILeaferImageSliceData.md"
  }, {
    "text": "ILeaferImageSlice",
    "link": "/api/interfaces/ILeaferImageSlice.md"
  }, {
    "text": "ILeaferImageLevel",
    "link": "/api/interfaces/ILeaferImageLevel.md"
  }, {
    "text": "ILeaferImage",
    "link": "/api/interfaces/ILeaferImage.md"
  }, {
    "text": "ILeaferImageMap",
    "link": "/api/interfaces/ILeaferImageMap.md"
  }, {
    "text": "ILeaferVideoConfig",
    "link": "/api/interfaces/ILeaferVideoConfig.md"
  }, {
    "text": "ILeaferVideo",
    "link": "/api/interfaces/ILeaferVideo.md"
  }, {
    "text": "ICursorTypeMap",
    "link": "/api/interfaces/ICursorTypeMap.md"
  }, {
    "text": "ICursorRotate",
    "link": "/api/interfaces/ICursorRotate.md"
  }, {
    "text": "ICursorRotateMap",
    "link": "/api/interfaces/ICursorRotateMap.md"
  }, {
    "text": "IInteraction",
    "link": "/api/interfaces/IInteraction.md"
  }, {
    "text": "IInteractionCanvas",
    "link": "/api/interfaces/IInteractionCanvas.md"
  }, {
    "text": "IInteractionConfig",
    "link": "/api/interfaces/IInteractionConfig.md"
  }, {
    "text": "IZoomConfig",
    "link": "/api/interfaces/IZoomConfig.md"
  }, {
    "text": "IMoveConfig",
    "link": "/api/interfaces/IMoveConfig.md"
  }, {
    "text": "IWheelConfig",
    "link": "/api/interfaces/IWheelConfig.md"
  }, {
    "text": "IPointerConfig",
    "link": "/api/interfaces/IPointerConfig.md"
  }, {
    "text": "ITouchConfig",
    "link": "/api/interfaces/ITouchConfig.md"
  }, {
    "text": "IMultiTouchConfig",
    "link": "/api/interfaces/IMultiTouchConfig.md"
  }, {
    "text": "ISingleGestureConfig",
    "link": "/api/interfaces/ISingleGestureConfig.md"
  }, {
    "text": "ICursorConfig",
    "link": "/api/interfaces/ICursorConfig.md"
  }, {
    "text": "ITransformer",
    "link": "/api/interfaces/ITransformer.md"
  }, {
    "text": "ILeafLayout",
    "link": "/api/interfaces/ILeafLayout.md"
  }, {
    "text": "ILayoutChangedData",
    "link": "/api/interfaces/ILayoutChangedData.md"
  }, {
    "text": "ILayoutBlockData",
    "link": "/api/interfaces/ILayoutBlockData.md"
  }, {
    "text": "IPartLayoutConfig",
    "link": "/api/interfaces/IPartLayoutConfig.md"
  }, {
    "text": "ILayouterConfig",
    "link": "/api/interfaces/ILayouterConfig.md"
  }, {
    "text": "ILayouter",
    "link": "/api/interfaces/ILayouter.md"
  }, {
    "text": "IPointData",
    "link": "/api/interfaces/IPointData.md"
  }, {
    "text": "IOptionPointData",
    "link": "/api/interfaces/IOptionPointData.md"
  }, {
    "text": "IUnitPointData",
    "link": "/api/interfaces/IUnitPointData.md"
  }, {
    "text": "IFromToData",
    "link": "/api/interfaces/IFromToData.md"
  }, {
    "text": "IRotationPointData",
    "link": "/api/interfaces/IRotationPointData.md"
  }, {
    "text": "IScrollPointData",
    "link": "/api/interfaces/IScrollPointData.md"
  }, {
    "text": "IClientPointData",
    "link": "/api/interfaces/IClientPointData.md"
  }, {
    "text": "IPoint",
    "link": "/api/interfaces/IPoint.md"
  }, {
    "text": "IRadiusPointData",
    "link": "/api/interfaces/IRadiusPointData.md"
  }, {
    "text": "ISizeData",
    "link": "/api/interfaces/ISizeData.md"
  }, {
    "text": "IOptionSizeData",
    "link": "/api/interfaces/IOptionSizeData.md"
  }, {
    "text": "ISize",
    "link": "/api/interfaces/ISize.md"
  }, {
    "text": "IScreenSizeData",
    "link": "/api/interfaces/IScreenSizeData.md"
  }, {
    "text": "IBoundsData",
    "link": "/api/interfaces/IBoundsData.md"
  }, {
    "text": "IOffsetBoundsData",
    "link": "/api/interfaces/IOffsetBoundsData.md"
  }, {
    "text": "IBoundsDataWithOptionRotation",
    "link": "/api/interfaces/IBoundsDataWithOptionRotation.md"
  }, {
    "text": "IBoundsDataFn",
    "link": "/api/interfaces/IBoundsDataFn.md"
  }, {
    "text": "IBounds",
    "link": "/api/interfaces/IBounds.md"
  }, {
    "text": "ITwoPointBoundsData",
    "link": "/api/interfaces/ITwoPointBoundsData.md"
  }, {
    "text": "IAutoBoxData",
    "link": "/api/interfaces/IAutoBoxData.md"
  }, {
    "text": "IAutoBoundsData",
    "link": "/api/interfaces/IAutoBoundsData.md"
  }, {
    "text": "IAutoBounds",
    "link": "/api/interfaces/IAutoBounds.md"
  }, {
    "text": "IMatrixData",
    "link": "/api/interfaces/IMatrixData.md"
  }, {
    "text": "IScaleData",
    "link": "/api/interfaces/IScaleData.md"
  }, {
    "text": "IScaleRotationData",
    "link": "/api/interfaces/IScaleRotationData.md"
  }, {
    "text": "ISkewData",
    "link": "/api/interfaces/ISkewData.md"
  }, {
    "text": "ILayoutData",
    "link": "/api/interfaces/ILayoutData.md"
  }, {
    "text": "ILayoutBoundsData",
    "link": "/api/interfaces/ILayoutBoundsData.md"
  }, {
    "text": "IMatrix",
    "link": "/api/interfaces/IMatrix.md"
  }, {
    "text": "IMatrixWithBoundsData",
    "link": "/api/interfaces/IMatrixWithBoundsData.md"
  }, {
    "text": "IMatrixWithScaleData",
    "link": "/api/interfaces/IMatrixWithScaleData.md"
  }, {
    "text": "IMatrixWithOptionScaleData",
    "link": "/api/interfaces/IMatrixWithOptionScaleData.md"
  }, {
    "text": "IMatrixWithOptionHalfData",
    "link": "/api/interfaces/IMatrixWithOptionHalfData.md"
  }, {
    "text": "IMatrixWithBoundsScaleData",
    "link": "/api/interfaces/IMatrixWithBoundsScaleData.md"
  }, {
    "text": "IMatrixWithLayoutData",
    "link": "/api/interfaces/IMatrixWithLayoutData.md"
  }, {
    "text": "MoveToCommandObject",
    "link": "/api/interfaces/MoveToCommandObject.md"
  }, {
    "text": "LineToCommandObject",
    "link": "/api/interfaces/LineToCommandObject.md"
  }, {
    "text": "BezierCurveToCommandObject",
    "link": "/api/interfaces/BezierCurveToCommandObject.md"
  }, {
    "text": "QuadraticCurveToCommandObject",
    "link": "/api/interfaces/QuadraticCurveToCommandObject.md"
  }, {
    "text": "IPathCommandNodeBase",
    "link": "/api/interfaces/IPathCommandNodeBase.md"
  }, {
    "text": "MoveToCommandNode",
    "link": "/api/interfaces/MoveToCommandNode.md"
  }, {
    "text": "LineToCommandNode",
    "link": "/api/interfaces/LineToCommandNode.md"
  }, {
    "text": "BezierCurveToCommandNode",
    "link": "/api/interfaces/BezierCurveToCommandNode.md"
  }, {
    "text": "ClosePathCommandNode",
    "link": "/api/interfaces/ClosePathCommandNode.md"
  }, {
    "text": "IPathNodeBase",
    "link": "/api/interfaces/IPathNodeBase.md"
  }, {
    "text": "IMotionPathData",
    "link": "/api/interfaces/IMotionPathData.md"
  }, {
    "text": "IPathDrawer",
    "link": "/api/interfaces/IPathDrawer.md"
  }, {
    "text": "IPathCreator",
    "link": "/api/interfaces/IPathCreator.md"
  }, {
    "text": "IPlatform",
    "link": "/api/interfaces/IPlatform.md"
  }, {
    "text": "IMiniappSelect",
    "link": "/api/interfaces/IMiniappSelect.md"
  }, {
    "text": "IMiniappSizeView",
    "link": "/api/interfaces/IMiniappSizeView.md"
  }, {
    "text": "IMiniapp",
    "link": "/api/interfaces/IMiniapp.md"
  }, {
    "text": "IPlugin",
    "link": "/api/interfaces/IPlugin.md"
  }, {
    "text": "IRenderOptions",
    "link": "/api/interfaces/IRenderOptions.md"
  }, {
    "text": "IRendererConfig",
    "link": "/api/interfaces/IRendererConfig.md"
  }, {
    "text": "IRenderer",
    "link": "/api/interfaces/IRenderer.md"
  }, {
    "text": "IPickResult",
    "link": "/api/interfaces/IPickResult.md"
  }, {
    "text": "IPickOptions",
    "link": "/api/interfaces/IPickOptions.md"
  }, {
    "text": "IPickBottom",
    "link": "/api/interfaces/IPickBottom.md"
  }, {
    "text": "ISelectorConfig",
    "link": "/api/interfaces/ISelectorConfig.md"
  }, {
    "text": "IFindCondition",
    "link": "/api/interfaces/IFindCondition.md"
  }, {
    "text": "IFindMethod",
    "link": "/api/interfaces/IFindMethod.md"
  }, {
    "text": "ISelectorProxy",
    "link": "/api/interfaces/ISelectorProxy.md"
  }, {
    "text": "ISelector",
    "link": "/api/interfaces/ISelector.md"
  }, {
    "text": "IPicker",
    "link": "/api/interfaces/IPicker.md"
  }, {
    "text": "IFinder",
    "link": "/api/interfaces/IFinder.md"
  }, {
    "text": "ITaskProcessorConfig",
    "link": "/api/interfaces/ITaskProcessorConfig.md"
  }, {
    "text": "ITaskProcessor",
    "link": "/api/interfaces/ITaskProcessor.md"
  }, {
    "text": "ITaskItem",
    "link": "/api/interfaces/ITaskItem.md"
  }, {
    "text": "ITaskOptions",
    "link": "/api/interfaces/ITaskOptions.md"
  }, {
    "text": "IWatchEventData",
    "link": "/api/interfaces/IWatchEventData.md"
  }, {
    "text": "IWatcherConfig",
    "link": "/api/interfaces/IWatcherConfig.md"
  }, {
    "text": "IWatcher",
    "link": "/api/interfaces/IWatcher.md"
  }, {
    "text": "IStyleAnimation",
    "link": "/api/interfaces/IStyleAnimation.md"
  }, {
    "text": "IKeyframesAnimation",
    "link": "/api/interfaces/IKeyframesAnimation.md"
  }, {
    "text": "IAnimateKeyframe",
    "link": "/api/interfaces/IAnimateKeyframe.md"
  }, {
    "text": "IComputedKeyframe",
    "link": "/api/interfaces/IComputedKeyframe.md"
  }, {
    "text": "IAnimate",
    "link": "/api/interfaces/IAnimate.md"
  }, {
    "text": "IAnimateList",
    "link": "/api/interfaces/IAnimateList.md"
  }, {
    "text": "ICachedShape",
    "link": "/api/interfaces/ICachedShape.md"
  }, {
    "text": "IStrokeAttrData",
    "link": "/api/interfaces/IStrokeAttrData.md"
  }, {
    "text": "IStrokeInputData",
    "link": "/api/interfaces/IStrokeInputData.md"
  }, {
    "text": "IStrokeStyle",
    "link": "/api/interfaces/IStrokeStyle.md"
  }, {
    "text": "IStrokeComputedData",
    "link": "/api/interfaces/IStrokeComputedData.md"
  }, {
    "text": "IStrokeComputedStyle",
    "link": "/api/interfaces/IStrokeComputedStyle.md"
  }, {
    "text": "ITextStyleAttrData",
    "link": "/api/interfaces/ITextStyleAttrData.md"
  }, {
    "text": "ITextStyleInputData",
    "link": "/api/interfaces/ITextStyleInputData.md"
  }, {
    "text": "ITextStyleComputedData",
    "link": "/api/interfaces/ITextStyleComputedData.md"
  }, {
    "text": "IEffectAttrData",
    "link": "/api/interfaces/IEffectAttrData.md"
  }, {
    "text": "IEffectInputData",
    "link": "/api/interfaces/IEffectInputData.md"
  }, {
    "text": "IEffectComputedData",
    "link": "/api/interfaces/IEffectComputedData.md"
  }, {
    "text": "IScrollConfig",
    "link": "/api/interfaces/IScrollConfig.md"
  }, {
    "text": "IScroller",
    "link": "/api/interfaces/IScroller.md"
  }, {
    "text": "ILine",
    "link": "/api/interfaces/ILine.md"
  }, {
    "text": "ILineData",
    "link": "/api/interfaces/ILineData.md"
  }, {
    "text": "ILineInputData",
    "link": "/api/interfaces/ILineInputData.md"
  }, {
    "text": "IArrow",
    "link": "/api/interfaces/IArrow.md"
  }, {
    "text": "IArrowData",
    "link": "/api/interfaces/IArrowData.md"
  }, {
    "text": "IArrowInputData",
    "link": "/api/interfaces/IArrowInputData.md"
  }, {
    "text": "ILinker",
    "link": "/api/interfaces/ILinker.md"
  }, {
    "text": "ILinkerPointData",
    "link": "/api/interfaces/ILinkerPointData.md"
  }, {
    "text": "ILinkerPointOptions",
    "link": "/api/interfaces/ILinkerPointOptions.md"
  }, {
    "text": "ILinkerComputedPointData",
    "link": "/api/interfaces/ILinkerComputedPointData.md"
  }, {
    "text": "ILinkerData",
    "link": "/api/interfaces/ILinkerData.md"
  }, {
    "text": "ILinkerInputData",
    "link": "/api/interfaces/ILinkerInputData.md"
  }, {
    "text": "IFlow",
    "link": "/api/interfaces/IFlow.md"
  }, {
    "text": "IFlowData",
    "link": "/api/interfaces/IFlowData.md"
  }, {
    "text": "IFlowInputData",
    "link": "/api/interfaces/IFlowInputData.md"
  }, {
    "text": "IRect",
    "link": "/api/interfaces/IRect.md"
  }, {
    "text": "IRectData",
    "link": "/api/interfaces/IRectData.md"
  }, {
    "text": "IRectInputData",
    "link": "/api/interfaces/IRectInputData.md"
  }, {
    "text": "IEllipse",
    "link": "/api/interfaces/IEllipse.md"
  }, {
    "text": "IEllipseData",
    "link": "/api/interfaces/IEllipseData.md"
  }, {
    "text": "IEllipseInputData",
    "link": "/api/interfaces/IEllipseInputData.md"
  }, {
    "text": "IPolygon",
    "link": "/api/interfaces/IPolygon.md"
  }, {
    "text": "IPolygonData",
    "link": "/api/interfaces/IPolygonData.md"
  }, {
    "text": "IPolygonInputData",
    "link": "/api/interfaces/IPolygonInputData.md"
  }, {
    "text": "IStar",
    "link": "/api/interfaces/IStar.md"
  }, {
    "text": "IStarData",
    "link": "/api/interfaces/IStarData.md"
  }, {
    "text": "IStarInputData",
    "link": "/api/interfaces/IStarInputData.md"
  }, {
    "text": "IPath",
    "link": "/api/interfaces/IPath.md"
  }, {
    "text": "IPathData",
    "link": "/api/interfaces/IPathData.md"
  }, {
    "text": "IPathInputData",
    "link": "/api/interfaces/IPathInputData.md"
  }, {
    "text": "IPen",
    "link": "/api/interfaces/IPen.md"
  }, {
    "text": "IPenData",
    "link": "/api/interfaces/IPenData.md"
  }, {
    "text": "IPenInputData",
    "link": "/api/interfaces/IPenInputData.md"
  }, {
    "text": "IText",
    "link": "/api/interfaces/IText.md"
  }, {
    "text": "IBackgroundBoxStyle",
    "link": "/api/interfaces/IBackgroundBoxStyle.md"
  }, {
    "text": "ITextData",
    "link": "/api/interfaces/ITextData.md"
  }, {
    "text": "ITextInputData",
    "link": "/api/interfaces/ITextInputData.md"
  }, {
    "text": "ITextRowData",
    "link": "/api/interfaces/ITextRowData.md"
  }, {
    "text": "ITextWordData",
    "link": "/api/interfaces/ITextWordData.md"
  }, {
    "text": "ITextCharData",
    "link": "/api/interfaces/ITextCharData.md"
  }, {
    "text": "ITextDrawData",
    "link": "/api/interfaces/ITextDrawData.md"
  }, {
    "text": "IImage",
    "link": "/api/interfaces/IImage.md"
  }, {
    "text": "IImageData",
    "link": "/api/interfaces/IImageData.md"
  }, {
    "text": "IImageInputData",
    "link": "/api/interfaces/IImageInputData.md"
  }, {
    "text": "ICanvas",
    "link": "/api/interfaces/ICanvas.md"
  }, {
    "text": "ICanvasData",
    "link": "/api/interfaces/ICanvasData.md"
  }, {
    "text": "ICanvasInputData",
    "link": "/api/interfaces/ICanvasInputData.md"
  }, {
    "text": "IFilm",
    "link": "/api/interfaces/IFilm.md"
  }, {
    "text": "IFilmData",
    "link": "/api/interfaces/IFilmData.md"
  }, {
    "text": "IFilmInputData",
    "link": "/api/interfaces/IFilmInputData.md"
  }, {
    "text": "IVideo",
    "link": "/api/interfaces/IVideo.md"
  }, {
    "text": "IVideoData",
    "link": "/api/interfaces/IVideoData.md"
  }, {
    "text": "IVideoInputData",
    "link": "/api/interfaces/IVideoInputData.md"
  }, {
    "text": "IRobot",
    "link": "/api/interfaces/IRobot.md"
  }, {
    "text": "IRobotActions",
    "link": "/api/interfaces/IRobotActions.md"
  }, {
    "text": "IRobotAnimation",
    "link": "/api/interfaces/IRobotAnimation.md"
  }, {
    "text": "IRobotKeyframe",
    "link": "/api/interfaces/IRobotKeyframe.md"
  }, {
    "text": "IRobotComputedKeyframe",
    "link": "/api/interfaces/IRobotComputedKeyframe.md"
  }, {
    "text": "IRobotData",
    "link": "/api/interfaces/IRobotData.md"
  }, {
    "text": "IRobotInputData",
    "link": "/api/interfaces/IRobotInputData.md"
  }, {
    "text": "ILeaferData",
    "link": "/api/interfaces/ILeaferData.md"
  }, {
    "text": "ILeaferInputData",
    "link": "/api/interfaces/ILeaferInputData.md"
  }, {
    "text": "IAppData",
    "link": "/api/interfaces/IAppData.md"
  }, {
    "text": "IAppInputData",
    "link": "/api/interfaces/IAppInputData.md"
  }, {
    "text": "IFrame",
    "link": "/api/interfaces/IFrame.md"
  }, {
    "text": "IFrameData",
    "link": "/api/interfaces/IFrameData.md"
  }, {
    "text": "IFrameInputData",
    "link": "/api/interfaces/IFrameInputData.md"
  }, {
    "text": "IBox",
    "link": "/api/interfaces/IBox.md"
  }, {
    "text": "IBoxData",
    "link": "/api/interfaces/IBoxData.md"
  }, {
    "text": "IBoxInputData",
    "link": "/api/interfaces/IBoxInputData.md"
  }, {
    "text": "IEllipseBox",
    "link": "/api/interfaces/IEllipseBox.md"
  }, {
    "text": "IEllipseBoxData",
    "link": "/api/interfaces/IEllipseBoxData.md"
  }, {
    "text": "IEllipseBoxInputData",
    "link": "/api/interfaces/IEllipseBoxInputData.md"
  }, {
    "text": "IPolygonBox",
    "link": "/api/interfaces/IPolygonBox.md"
  }, {
    "text": "IPolygonBoxData",
    "link": "/api/interfaces/IPolygonBoxData.md"
  }, {
    "text": "IPolygonBoxInputData",
    "link": "/api/interfaces/IPolygonBoxInputData.md"
  }, {
    "text": "IStarBox",
    "link": "/api/interfaces/IStarBox.md"
  }, {
    "text": "IStarBoxData",
    "link": "/api/interfaces/IStarBoxData.md"
  }, {
    "text": "IStarBoxInputData",
    "link": "/api/interfaces/IStarBoxInputData.md"
  }, {
    "text": "IPathBox",
    "link": "/api/interfaces/IPathBox.md"
  }, {
    "text": "IPathBoxData",
    "link": "/api/interfaces/IPathBoxData.md"
  }, {
    "text": "IPathBoxInputData",
    "link": "/api/interfaces/IPathBoxInputData.md"
  }, {
    "text": "IImageBox",
    "link": "/api/interfaces/IImageBox.md"
  }, {
    "text": "IImageBoxData",
    "link": "/api/interfaces/IImageBoxData.md"
  }, {
    "text": "IImageBoxInputData",
    "link": "/api/interfaces/IImageBoxInputData.md"
  }, {
    "text": "IGroup",
    "link": "/api/interfaces/IGroup.md"
  }, {
    "text": "IGroupData",
    "link": "/api/interfaces/IGroupData.md"
  }, {
    "text": "IGroupInputData",
    "link": "/api/interfaces/IGroupInputData.md"
  }, {
    "text": "IUI",
    "link": "/api/interfaces/IUI.md"
  }, {
    "text": "IStateStyle",
    "link": "/api/interfaces/IStateStyle.md"
  }, {
    "text": "IStates",
    "link": "/api/interfaces/IStates.md"
  }, {
    "text": "IFindUIMethod",
    "link": "/api/interfaces/IFindUIMethod.md"
  }, {
    "text": "IUIData",
    "link": "/api/interfaces/IUIData.md"
  }, {
    "text": "IUIBaseInputData",
    "link": "/api/interfaces/IUIBaseInputData.md"
  }, {
    "text": "IUIInputData",
    "link": "/api/interfaces/IUIInputData.md"
  }, {
    "text": "IUIJSONData",
    "link": "/api/interfaces/IUIJSONData.md"
  }, {
    "text": "IApp",
    "link": "/api/interfaces/IApp.md"
  }, {
    "text": "IAppConfig",
    "link": "/api/interfaces/IAppConfig.md"
  }, {
    "text": "IAppForEachFunction",
    "link": "/api/interfaces/IAppForEachFunction.md"
  }, {
    "text": "ILeafer",
    "link": "/api/interfaces/ILeafer.md"
  }, {
    "text": "IEditorBase",
    "link": "/api/interfaces/IEditorBase.md"
  }, {
    "text": "ITransformTool",
    "link": "/api/interfaces/ITransformTool.md"
  }, {
    "text": "IEditorConfig",
    "link": "/api/interfaces/IEditorConfig.md"
  }, {
    "text": "IEditorSelectData",
    "link": "/api/interfaces/IEditorSelectData.md"
  }, {
    "text": "IEditorEditOuterData",
    "link": "/api/interfaces/IEditorEditOuterData.md"
  }, {
    "text": "IEditorMoveData",
    "link": "/api/interfaces/IEditorMoveData.md"
  }, {
    "text": "IEditorScaleData",
    "link": "/api/interfaces/IEditorScaleData.md"
  }, {
    "text": "IEditorRotationData",
    "link": "/api/interfaces/IEditorRotationData.md"
  }, {
    "text": "IEditorSkewData",
    "link": "/api/interfaces/IEditorSkewData.md"
  }, {
    "text": "IEditorBeforeSelect",
    "link": "/api/interfaces/IEditorBeforeSelect.md"
  }, {
    "text": "IEditorBeforeEditOuter",
    "link": "/api/interfaces/IEditorBeforeEditOuter.md"
  }, {
    "text": "IEditorBeforeEditInner",
    "link": "/api/interfaces/IEditorBeforeEditInner.md"
  }, {
    "text": "IEditorBeforeMove",
    "link": "/api/interfaces/IEditorBeforeMove.md"
  }, {
    "text": "IEditorBeforeScale",
    "link": "/api/interfaces/IEditorBeforeScale.md"
  }, {
    "text": "IEditorBeforeRotate",
    "link": "/api/interfaces/IEditorBeforeRotate.md"
  }, {
    "text": "IEditorBeforeSkew",
    "link": "/api/interfaces/IEditorBeforeSkew.md"
  }, {
    "text": "IEditorOnCopy",
    "link": "/api/interfaces/IEditorOnCopy.md"
  }, {
    "text": "IEditPointInputData",
    "link": "/api/interfaces/IEditPointInputData.md"
  }, {
    "text": "IEditPoint",
    "link": "/api/interfaces/IEditPoint.md"
  }, {
    "text": "IEditBoxBase",
    "link": "/api/interfaces/IEditBoxBase.md"
  }, {
    "text": "IEditorDragStartData",
    "link": "/api/interfaces/IEditorDragStartData.md"
  }, {
    "text": "IEditorConfigFunction",
    "link": "/api/interfaces/IEditorConfigFunction.md"
  }, {
    "text": "IEditToolFunction",
    "link": "/api/interfaces/IEditToolFunction.md"
  }, {
    "text": "IColorConvertModule",
    "link": "/api/interfaces/IColorConvertModule.md"
  }, {
    "text": "IEffectModule",
    "link": "/api/interfaces/IEffectModule.md"
  }, {
    "text": "IExportModule",
    "link": "/api/interfaces/IExportModule.md"
  }, {
    "text": "IFilterModule",
    "link": "/api/interfaces/IFilterModule.md"
  }, {
    "text": "IFilterProcessor",
    "link": "/api/interfaces/IFilterProcessor.md"
  }, {
    "text": "IFilterFunction",
    "link": "/api/interfaces/IFilterFunction.md"
  }, {
    "text": "IPaintModule",
    "link": "/api/interfaces/IPaintModule.md"
  }, {
    "text": "IPaintImageModule",
    "link": "/api/interfaces/IPaintImageModule.md"
  }, {
    "text": "IPaintGradientModule",
    "link": "/api/interfaces/IPaintGradientModule.md"
  }, {
    "text": "IPathArrowModule",
    "link": "/api/interfaces/IPathArrowModule.md"
  }, {
    "text": "IStateModule",
    "link": "/api/interfaces/IStateModule.md"
  }, {
    "text": "ITextConvertModule",
    "link": "/api/interfaces/ITextConvertModule.md"
  }, {
    "text": "ITransitionModule",
    "link": "/api/interfaces/ITransitionModule.md"
  }, {
    "text": "ITransitionMap",
    "link": "/api/interfaces/ITransitionMap.md"
  }, {
    "text": "ITransitionFunction",
    "link": "/api/interfaces/ITransitionFunction.md"
  }, {
    "text": "ILeafPaint",
    "link": "/api/interfaces/ILeafPaint.md"
  }, {
    "text": "ILeafPaintPatternData",
    "link": "/api/interfaces/ILeafPaintPatternData.md"
  }, {
    "text": "ILeafStrokePaint",
    "link": "/api/interfaces/ILeafStrokePaint.md"
  }, {
    "text": "ILeafShadowEffect",
    "link": "/api/interfaces/ILeafShadowEffect.md"
  }, {
    "text": "IPaintBase",
    "link": "/api/interfaces/IPaintBase.md"
  }, {
    "text": "ISolidPaint",
    "link": "/api/interfaces/ISolidPaint.md"
  }, {
    "text": "IStrokeSolidPaint",
    "link": "/api/interfaces/IStrokeSolidPaint.md"
  }, {
    "text": "IRGB",
    "link": "/api/interfaces/IRGB.md"
  }, {
    "text": "IRGBA",
    "link": "/api/interfaces/IRGBA.md"
  }, {
    "text": "IGradientPaint",
    "link": "/api/interfaces/IGradientPaint.md"
  }, {
    "text": "IStrokeGradientPaint",
    "link": "/api/interfaces/IStrokeGradientPaint.md"
  }, {
    "text": "IColorStop",
    "link": "/api/interfaces/IColorStop.md"
  }, {
    "text": "IImagePaint",
    "link": "/api/interfaces/IImagePaint.md"
  }, {
    "text": "IStrokeImagePaint",
    "link": "/api/interfaces/IStrokeImagePaint.md"
  }, {
    "text": "IImageFilter",
    "link": "/api/interfaces/IImageFilter.md"
  }, {
    "text": "IArrowTypeData",
    "link": "/api/interfaces/IArrowTypeData.md"
  }, {
    "text": "IPathDataArrowMap",
    "link": "/api/interfaces/IPathDataArrowMap.md"
  }, {
    "text": "IPathDataArrow",
    "link": "/api/interfaces/IPathDataArrow.md"
  }, {
    "text": "IPathDataArrowOffset",
    "link": "/api/interfaces/IPathDataArrowOffset.md"
  }, {
    "text": "ITextDecorationData",
    "link": "/api/interfaces/ITextDecorationData.md"
  }, {
    "text": "IVectorPath",
    "link": "/api/interfaces/IVectorPath.md"
  }, {
    "text": "IShadowEffect",
    "link": "/api/interfaces/IShadowEffect.md"
  }, {
    "text": "IBlurEffect",
    "link": "/api/interfaces/IBlurEffect.md"
  }, {
    "text": "IGrayscaleEffect",
    "link": "/api/interfaces/IGrayscaleEffect.md"
  }, {
    "text": "IEffect",
    "link": "/api/interfaces/IEffect.md"
  }],
  "collapsed": true
}];